// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvfpbjrdjczpstrwghxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZnBianJkamN6cHN0cndnaHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTkyNDAsImV4cCI6MjA1OTk3NTI0MH0.ucmAXD6KhAVhyc2Cx2l0LvolnSHBhtjLddwWFRGP8m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);